INSERT INTO genres(name) VALUES('Biographical Picture');
INSERT INTO genres(name) VALUES('Sureal');
INSERT INTO genres(name) VALUES('Cartoon');
INSERT INTO genres(name) VALUES('Violence');
INSERT INTO genres(name) VALUES('Romantic');
INSERT INTO genres(name) VALUES('Pornography');
INSERT INTO genres(name) VALUES('Disaster');
INSERT INTO genres(name) VALUES('Epic');
INSERT INTO genres(name) VALUES('Black');
INSERT INTO genres(name) VALUES('TV Show');
INSERT INTO genres(name) VALUES('Cops and Robbers');
INSERT INTO genres(name) VALUES('Now-camp');
INSERT INTO genres(name) VALUES('Avant Garde');
